### ISSUE TITLE
Compiler warning in GetColor()

### ISSUE THREAD

**Issue by unclejimbo** [yuki-koyama/tinycolormap#23]
Compiler: gcc-10.1

> In file included from /home/unclejimbo/Workspace/tinycolormap/tools/png-exporter/main.cpp:3:
[build] /home/unclejimbo/Workspace/tinycolormap/include/tinycolormap.hpp: In function ‘tinycolormap::Color tinycolormap::GetColor(double, tinycolormap::ColormapType)’:
[build] /home/unclejimbo/Workspace/tinycolormap/include/tinycolormap.hpp:142:5: warning: control reaches end of non-void function [-Wreturn-type]
[build]   142 |     }
[build]       | 

Should add a return value for the default case to eliminate this warning, maybe Civids since it's the default parameter.

**Comment by yuki-koyama** [comment]
Thanks! Let me know if the warning still appears.
