### ISSUE TITLE
TODO: Update the list of the projects using tinycolormap

### ISSUE THREAD

**Issue by yuki-koyama** [yuki-koyama/tinycolormap#34]
https://github.com/Siv3D/OpenSiv3D/commit/84aa35f561eccb9ea7e58f50a5f007af7bde5383
https://twitter.com/Reputeless/status/1334137711033159680

**Comment by ThFriedrich** [comment]
I am using tinycolormap in my project too:
[https://github.com/ThFriedrich/riCOM_cpp](https://github.com/ThFriedrich/riCOM_cpp)

**Comment by yuki-koyama** [comment]
Great, thank you for letting me know!
