### ISSUE TITLE
FeatureRequest: Add cubehelix color map

### ISSUE THREAD

**Issue by cosmonaut** [yuki-koyama/tinycolormap#40]
Would love to see the cubehelix colormap (or even a few varieties) as part of this library. 

Quick references:
https://github.com/jradavenport/cubehelix
https://ui.adsabs.harvard.edu/abs/2011BASI...39..289G/abstract

**Comment by ChaseDurand** [comment]
I've opened pull request #41 to add the default cubehelix palette.

**Comment by yuki-koyama** [comment]
I've merged the PR. Thank you very much for the suggestion and the PR!
